### PR TITLE
feat(formula): rewrite, align to template formula

### PR DESCRIPTION
**Pull request by noelmcloughlin**
BREAKING CHANGE: Major refactor of formula to bring it in alignment with the
template-formula. As with all substantial changes, please ensure your
existing configurations work in the ways you expect from this formula.

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES

### Related issues and/or pull requests

#7 and #8

### Proposed changes

This formula has not been updated since 2014.

This PR is a complete rewrite to align with template-formula:

- align to template formula (semantic release, travis CI/CD, listing, etc)
- Support for multiple JDK/JRE providers; AdoptOpenJDK, Amazon Corretto, Graalvm, Haikuvm, Intellij JDK, Oracle, and Zulu.

The default provider is AdoptOpenJDK but that is configurable via pillar.

These following tests passed on Ubuntu and were included in CI/CD.

AdoptOpenJDK 8
Amazon Corretto 8
Graalvm 8
Haikuvm (8)
Intellij JRE 8
Zulu 8

Oracle is not fully tested yet because it is hard (impossible) to download JDK/JRE from Oracle OTN due to login stuff. Some other mirror is needed before adding Oracle to Travis CI/CD (same issue with sqlplus and SQL developer formula).

This formula conflicts with sun-java-formula because of both use java for pillar data.
However, that situation existed before this PR.

**Pillar / config required to test the proposed changes**

Only if you want to change default pillars.

```
java:
  provider: adopt
  release: 8
```
Valid providers: adopt, amazon, graalvm, haikuvm, intellij, oracle, and zulu.
Valid releases are 8, 11, 14, etc.
You are responsible for proving checksums pillar data if you change Java versions.

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@sticky-note This is part of a series of 30 formulas/PRs that need to be reviewed!  For more information, see here:

* https://tree.taiga.io/project/myii-saltstack-formulas/taskboard/meeting-002

You're welcome to join in and interact on Taiga.  Please contact me in Slack and give me the e-mail address you use with GitHub -- that way, you can log into Taiga by using your GitHub integration.

**Comment by noelmcloughlin** [comment]
Hi @myii  could I merge this? The formula was not updated since 2014. Fixes open issues.

**Comment by myii** [comment]
> Hi @myii could I merge this? The formula was not updated since 2014. Fixes open issues.

@noelmcloughlin This is next on my list.  After that, it's all of the new formulas that we discussed; do you still want to transfer them to the org or shall I just get on with adding them to the `ssf-formula`?

**Comment by noelmcloughlin** [comment]
> do you still want to transfer them to the org or shall I just get on with adding them to the `ssf-formula`?

What do you recommend?  
If there is a list then I could work of that (all my new formulas plus what?).
Can we raise a bug on Github for the problem?

**Comment by noelmcloughlin** [comment]
Reminder: 
Oracle is not part of Travis CI because it's behind login wall and even if we get it working today (accept license using curl) it will break next time Oracle updates version.   There is discussion here: https://github.com/saltstack-formulas/sqlplus-formula/pull/17#issuecomment-638487889

This does not block the PR (but an issue is needed on backlog afterwards).

**Comment by myii** [comment]
> What do you recommend?
> If there is a list then I could work of that (all my new formulas plus what?).
> Can we raise a bug on Github for the problem?

@noelmcloughlin Everything is on the current sprint in Taiga:

* https://tree.taiga.io/project/myii-saltstack-formulas/taskboard/meeting-004

Scroll down to user story `#237 [M00X] Add new formulas implementing `semantic-release`: ensure new formulas adopt the standardised structure across the org` and you'll see all of the task cards under the `IN PROGRESS` column.  As you complete each one, please slide the task over into the `READY FOR REVIEW` column.

There's no major hurry, we can do a couple first and see how it goes.  It will take me some time to get them added to the `ssf-formula` anyway.

**Comment by myii** [comment]
Merged, thanks for the patience @noelmcloughlin.

Added another commit 547c09f, including:

* Use `saltimages` instead of `netmanagers` as the Docker Hub source for pre-salted images (this is the new official source going forwards).
* Resolve `yamllint` issues in `defaults.yaml`.
* Resolve `rubocop` violation in ` test/integration/adopt/controls/default_spec.rb`.
* Fix suite names in all InSpec related files.

**Pull request merged**
