### PR TITLE
refactor(formula): rewrite; align to template-formula

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES

### Related issues and/or pull requests

#8 
#7 

### Describe the changes you're proposing

This formula has not been updated since 2014.

This PR is a complete rewrite to align with template-formula. I have added multiple features:
- align to template formula (semantic release, travis CI/CD, listing, etc)
- Support for multiple JDK/JRE providers;  AdoptOpenJDK, Amazon Corretto, Graalvm, Haikuvm, Intellij JDK, Oracle, and Zulu.

The default provider is AdoptOpenJDK but that is configurable via pillar.

These following tests passed on Ubuntu and were included in CI/CD.
- AdoptOpenJDK 8
- Amazon Corretto 8
- Graalvm 8
- Haikuvm (8)
- Intellij JRE 8
- Zulu 8

Oracle is not fully tested yet because it is hard (impossible) to download JDK/JRE from Oracle OTN due to login stuff. Some other mirror is needed before adding Oracle to Travis CI/CD (same issue with sqlplus and SQL developer formula).

This formula conflicts with sun-java-formula because of both use `java` for pillar data. 
However, that situation existed before this PR.

### Pillar / config required to test the proposed changes

Only if you want to change default pillars.
```
java:
  provider: adopt
  release: 8
```

Valid providers are `adopt, amazon, graalvm, haikuvm, intellij, oracle`, and `zulu`.
Valid releases are `8`, `11`, `14`, etc.
You are responsible for proving checksums pilalr data if you change Java versions.

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

Issue #5 (Ubuntu PPA) is not fixed by this PR. Further work is needed to clarify https://gist.github.com/renoirb/6722890 and address #5

### CODE REVIEW

**Comment by myii** [comment]
It joins the (long) queue to be reviewed:

* https://tree.taiga.io/project/myii-saltstack-formulas/task/170
* https://tree.taiga.io/project/myii-saltstack-formulas/task/171

I actually didn't know there were so many (new and modified formulas) until I put them all on the taskboard!

**Comment by noelmcloughlin** [comment]
One state fails on all Travis jobs - I have not figured out the root cause.
```
       ----------
                 ID: java-environ-file-install-file-managed
           Function: file.managed
               Name: /etc/default/java.sh
             Result: False
            Comment: The following requisites were not found:
                                 require:
                                     id: java.archive
            Started: 01:34:44.491607
           Duration: 0.002 ms
            Changes:   
```

**Comment by noelmcloughlin** [comment]
Hi @myii 
I have finished the project I was working on so this is my last PR needed.
Tomorrow I will tidy up things on the backlog of refactored formulas.
- update commit with BREAKING CHANGE
- Some other stuff on my end.

If you can find the reason for the failed state that would be nice - I cannot see the problem.

Thanks
Noel

**Comment by myii** [comment]
> If you can find the reason for the failed state that would be nice - I cannot see the problem.

@noelmcloughlin That's precisely why we don't comment out [this line](https://github.com/saltstack-formulas/java-formula/pull/9/files#diff-fdbca9ed07a634829a3548f874dc925aR159):

```yaml
  # log_level: debug
```

It then becomes easy to see how the state is rendered, to figure out what's going on.

**Comment by noelmcloughlin** [comment]
I am noting one infra problem regarding oracle software.

`java-formula`, `sqlplus-formula` and  `sqldeveloper-formula` software are stored on Oracle OTN URLs (login protected, its complicated).  If this community could provide a mirror to store sqlplus, java, sqldeveloper binaries then that would be great. Otherwise it is not feasible to add these three formulas to Travis CI/CD where Oracle software is concerned.

**Comment by noelmcloughlin** [comment]
> It then becomes easy to see how the state is rendered, to figure out what's going on.

Ahh yeah.  I disabled that one/two new formulae because Travis job logs were too big (archive.extracted & file.absent can be very verbose) when in same high state.  I will enable on this formula. thx

**Comment by myii** [comment]
> ... archive.extracted & file.absent can be very verbose in same high state.

@noelmcloughlin You can send `options` through to the `archive.extracted` state, in order to suppress the verbosity.  The example in the docs shows how to increase the verbosity but I'm sure you can find the opposite option.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html

> 2. tar archive with flag for verbose output, and enforcement of user/group ownership:
> 
> ```yaml
> graylog2-server:
>   archive.extracted:
>     - name: /opt/
>     - source: https://github.com/downloads/Graylog2/graylog2-server/graylog2-server-0.9.6p1.tar.gz
>     - source_hash: md5=499ae16dcae71eeb7c3a30c75ea7a1a6
>     - options: v
>     - user: foo
>     - group: foo
> ```

**Comment by noelmcloughlin** [comment]
> You can send `options` through to the `archive.extracted` state

So for `archive.extracted` I can add `trim_output: true`.   For `file.absent, recurse: true` the volume output on large (archive) subdirectories can be crazy, but maybe I need to revisit my `formula.archive` state pattern to see if I'm doing something wrong.

**Comment by noelmcloughlin** [comment]
Just noticed commit history is messed up - Opening new PR.

**Pull request closed without merging**
