### PR TITLE
test(map): verify `map.jinja` dump using `_mapdata` state

### PR DESCRIPTION
**Pull request by baby-gnu**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Verify the `map.jinja` dump using `_mapdata` state

### Debug log showing how the proposed changes work

```
  ✔  java._mapdata: `map.jinja` should match the reference file
     ✔  File content should match profile map data exactly
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by myii — APPROVED** [review]
Checked using https://github.com/myii/ssf-formula/pull/296.  The changes to `.rubocop.yml` and `_mapdata.rb` will be propagated to all formulas using that PR.

**Comment by myii** [comment]
Nice PR, @baby-gnu!  Merged.

**Comment by myii** [comment]
@baby-gnu Actually, one more thing you could do that would be useful.  Would you mind adding a small comment to https://github.com/myii/ssf-formula/pull/296, explaining why we're moving to `YAML.load` instead?  That will help if anyone links back to that PR from any of the formulas.

**Comment by baby-gnu** [comment]
@myii sure, I used the commit message of https://github.com/saltstack-formulas/java-formula/pull/15/commits/f9ca0e2c245c61cd9c4e532efc91745f34e5337f as a the comment https://github.com/myii/ssf-formula/pull/296#issuecomment-784524758

**Pull request merged**
