### PR TITLE
feat(map): update to v5 `map.jinja`

### PR DESCRIPTION
**Pull request by baby-gnu**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Yes.

BREAKING CHANGE: `map.jinja` now export a generic `mapdata` variable

BREAKING CHANGE: The parameters per grains are now under `java/parameters/`

### Describe the changes you're proposing

`map.jinja` is now generic, the post-processing is now done in `java/post-map.jinja`.

The `java-formula` requires a dedicated `map.jinja` configuration to load values for the `kernel` grains.

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
Nice finale for this series of PRs, @baby-gnu!  All good from my end but I'll just leave time for @noelmcloughlin, who is the main code owner here.

**Comment by baby-gnu** [comment]
It looks like I changed the order in which the values are loaded from the YAML files:

- [previously](https://github.com/saltstack-formulas/java-formula/blob/d0c1af8/java/map.jinja#L10-L17)
  1. `defaults.yaml`
  2. `os_family`
  3. `osarch`
  4. `kernel`
  5. `salt['config.get']("java:lookup")`
  6. `salt['config.get']("java")`
- this PR
  1. `defaults.yaml`
  2. `osarch`
  3. `os_family`
  4. `os`
  5. `osfinger`
  6. `kernel`
  7. `salt['config.get']("java:lookup")`
  8. `salt['config.get']("java")`
  9. `id`

I can modify `parameters/map_jinja.yaml` to use the same order as before or maybe add a `BREAKING CHANGE` to say that the ordering is now changed?

**Review by noelmcloughlin — APPROVED** [review]
Looks good to me. thanks.

**Comment by noelmcloughlin** [comment]
> It looks like I changed the order in which the values are loaded from the YAML files:

Only if you are aware it causes a problem I guess.
I think this repo mainly manages archives so ordering might not be improtant for archives.

**Pull request merged**
